---

  - name: install dependencies
    yum:
      name={{ item }}
      state=present
    with_items:
      - nagios
      - nagios-nrpe
      - nagios-plugins-all
      - nagios-plugins-nrpe

  - name: Enable NRPE command
    copy:
      src=commands.cfg
      dest=/etc/nagios/objects/commands.cfg

  - name: Enable notifications for localhost
    copy:
      src=localhost.cfg
      dest=/etc/nagios/objects/localhost.cfg

  - name: NRPE add nagios in allowed_hosts
    lineinfile:
      dest="/etc/nagios/nrpe.cfg"
      regexp="^allowed_hosts=127.0.0.1"
      line="allowed_hosts=127.0.0.1,10.0.2.0/24,192.168.100.0/24"


  - name: start nagios,nrpe,httpd service
    service:
      name={{ item }}
      state=started
      enabled=yes
    with_items:
      - nagios
      - nrpe
      - httpd
