Vagrant.configure(2) do |config|
  config.vm.box = "centos7.0"
  config.ssh.insert_key = false
  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "1024"]
    vb.customize ["modifyvm", :id, "--cpus", "1"]
  end
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.network "private_network", ip: "192.168.100.50"
  config.vm.provision :shell, inline: """
    sudo service firewalld stop && \
         systemctl disable firewalld &&
         yum clean all &&
         yum install tomcat net-tools -y &&
         service tomcat start
  """
end
