Vagrant.configure(2) do |config|
  config.vm.box = "bento/centos-7.1"
  config.ssh.insert_key = false
  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "1024"]
    vb.customize ["modifyvm", :id, "--cpus", "1"]
  end
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.network "private_network", ip: "192.168.101.50"
  config.vm.provision :shell, inline: """
    rm -rf /etc/yum.repos.d/*;
    echo '192.168.101.12        artifactory' >> /etc/hosts;
    cat <<EOF >> /etc/yum.repos.d/centos-artifactory.repo
[base]
name=CentOS-7 - Base
baseurl=http://artifactory:8081/artifactory/centos-7-base/
enabled=1
gpgcheck=0

[updates]
name=CentOS-7 - Updates
baseurl=http://artifactory:8081/artifactory/centos-7-updates/
enabled=1
gpgcheck=0

[extras]
name=CentOS-7 - Extras
baseurl=http://artifactory:8081/artifactory/centos-7-extras/
enabled=0
gpgcheck=0
EOF
    sudo service firewalld stop && \
         systemctl disable firewalld &&
         yum clean all &&
         yum install tomcat net-tools -y &&
         service tomcat start
  """
end
