---

  recreate_repo: False
  api_url: "http://artifactory:8081/artifactory/api"
  api_username: "admin"
  api_password: "password"
  artifactory_repo_base_url: "http://artifactory:8081/artifactory"
  artifactory_repos:
  -  {repo_type: "yum", repo_key: 'jenkins-stable', remote_url: 'http://pkg.jenkins-ci.org/redhat-stable/'}
  -  {repo_type: "yum", repo_key: "centos-7-base", remote_url: "http://mirror.centos.org/centos/7/os/x86_64/"}
  -  {repo_type: "yum", repo_key: "centos-7-updates", remote_url: "http://mirror.centos.org/centos/7/updates/x86_64/"}
  -  {repo_type: "yum", repo_key: "centos-7-extras", remote_url: "http://mirror.centos.org/centos/7/extras/x86_64/"}
  -  {repo_type: "yum", repo_key: "centos-7-plus", remote_url: "http://mirror.centos.org/centos/7/centosplus/x86_64/"}
  -  {repo_type: "yum", repo_key: "centos-7-base-sources", remote_url: "http://vault.centos.org/centos/7/os/Source/"}
  -  {repo_type: "yum", repo_key: "centos-7-updates-sources", remote_url: "http://vault.centos.org/centos/7/updates/Source/"}
  -  {repo_type: "yum", repo_key: "centos-7-extras-sources", remote_url: "http://vault.centos.org/centos/7/extras/Source/"}
  -  {repo_type: "yum", repo_key: "centos-7-plus-sources", remote_url: "http://vault.centos.org/centos/7/centosplus/Source/"}
  -  {repo_type: "yum", repo_key: "elastic-2.x-elasticsearch", remote_url: "http://packages.elastic.co/elasticsearch/2.x/centos/"}
  -  {repo_type: "yum", repo_key: "elastic-2.1-logstash", remote_url: "http://packages.elastic.co/logstash/2.1/centos/"}
  -  {repo_type: "yum", repo_key: "elastic-2.1-logstash-forwarder", remote_url: "http://packages.elastic.co/logstashforwarder/centos/"}
  -  {repo_type: "yum", repo_key: "epel-7-base", remote_url: "https://dl.fedoraproject.org/pub/epel/7/x86_64/"}
#  -  {repo_type: "yum", repo_key: "epel-7-source", remote_url: "http://download.fedoraproject.org/pub/epel/7/SRPMS/"}
  -  {repo_type: "maven", repo_key: "jboss-public", remote_url: "https://repository.jboss.org/nexus/content/groups/public/"}
  centos_default_yum_repos_keys: ['Base', 'Updates', 'Extras', 'Plus']
  jdk_version: '8u65-b17'
  jdk_install_base: "/opt/jdk"
  jdk_install_path: "{{jdk_install_base}}/{{jdk_version}}"
  jdk_archive: "jdk-{{jdk_version.split('-')[0]}}-linux-{{ansible_architecture.replace('86_','')}}.tar.gz"
  #jdk_download_url: "http://download.oracle.com/otn-pub/java/jdk/{{jdk_version}}/{{jdk_archive}}"
  #jdk_repo_url: "http://artifactory:8081/artifactory/local-generic/oracle/jdk/jdk-8u65/jdk-8u65-linux-x64.tar.gz"
