---

  - name: ensure these entries exists in etc-hosts
    lineinfile:
      line="{{ item }}"
      state=present
      dest=/etc/hosts
    with_items:
      - '192.168.101.11   proxy'
      - '192.168.101.12   oracle'
      - '192.168.101.13   artifactory'
      - '192.168.101.14   bitbucket'
      - '192.168.101.15   jira'
      - '192.168.101.16   jenkins'
      - '192.168.101.17   elk'
      - '192.168.101.18   nagios'
      - '192.168.101.50   tomcat'
