---

  # ==========================
  # create repo in artifactory
  # ---------------------------
  - name: check if artifactory is up
    shell:
      timeout 1 bash -c "cat < /dev/null > /dev/tcp/artifactory/8081"
    register: artifactory_check_result
    until: artifactory_check_result.rc == 0
    retries: 3
    delay: 1
    ignore_errors: yes
    tags: local_repo

  - name: set facts
    set_fact:
      artifactory_up="{{ artifactory_check_result.rc == 0}}"
    tags: local_repo

  - debug: var=artifactory_up

#  - name: remove repo in artifactory
#    sudo: no
#    delegate_to: localhost
#    artifactory_repo:
#      state=absent
#      api_url="{{api_url}}"
#      api_username="{{api_username}}"
#      api_password="{{api_password}}"
#      repo_key="{{item.repo_key}}"
#    with_items: artifactory_repos
#    run_once: true
#    when: recreate_repo and artifactory_up

  - name: create remote remote repos in artifactory
    sudo: no
    delegate_to: localhost
    artifactory_repo:
      state="present"
      api_url="{{api_url}}"
      api_username="{{api_username}}"
      api_password="{{api_password}}"
      rclass="remote"
      repo_key="{{item.repo_key}}"
      package_type="{{item.repo_type}}"
      remote_url="{{item.remote_url}}"
    with_items: artifactory_repos
    run_once: true
    when: artifactory_up
    tags: local_repo

  # ==========================
  # remove existing yum repos
  # --------------------------
  - name: remove existing yum repo files
    shell: >
      cd /etc/yum.repos.d/;
      for f in `ls *.repo`; do
        mv $f _$f.notuse;
      done;
    args:
      creates: /etc/yum.repos.d/_CentOS-Base.repo.notuse
    when: artifactory_up
    tags: local_repo

  # ========================================
  # add references to artifactory yum repos
  # ----------------------------------------

  - name: create new yum entries pointing to artifactory
    yumrepo:
      name={{item.repo_key}}
      baseurl="{{artifactory_repo_base_url}}/{{item.repo_key}}"
      file=artifactory
      owner=root
      mode=0644
      enabled=yes
      gpgcheck=no
    with_items: "{{artifactory_repos|selectattr('repo_type','equalto','yum')|list}}"
    when: artifactory_up
    tags: local_repo
