---

  - name: copy oracle tablespace sql script
    template: src=tablespace.sql.j2 dest=/tmp/{{ schema_name }}_tablespace.sql owner=oracle group=dba mode=0500
    register: test_tablespace_sql_script

  - name: copy oracle role sql script
    template: src=role.sql.j2 dest=/tmp/{{ schema_name }}_role.sql owner=oracle group=dba mode=0500
    register: test_role_sql_script

  - name: copy oracle role sql script
    template: src=schema.sql.j2 dest=/tmp/{{ schema_name }}_user.sql owner=oracle group=dba mode=0500
    register: test_schema_sql_script

  - name: copy oracle datadump sql script
    template: src=datadump.sql.j2 dest=/tmp/{{ schema_name }}_datadump.sql owner=oracle group=dba mode=0500
    register: test_datadump_sql_script

  - name: copy datadump if specified
    copy:
      src={{schema_dump}}.dmp
      dest=/tmp/{{schema_dump}}.dmp
      owner=oracle
    when: schema_dump|default("") != ""


  - name: create tablespace
    shell: >
      source ~oracle/.bashrc && \
        sqlplus sys/{{ oracle_system_pwd }} as sysdba < /tmp/{{ schema_name }}_tablespace.sql
    sudo_user: oracle
    when: test_tablespace_sql_script|changed

  - name: create role
    shell: >
      source ~oracle/.bashrc && \
        sqlplus sys/{{ oracle_system_pwd }} as sysdba < /tmp/{{ schema_name }}_role.sql
    sudo_user: oracle
    when: test_role_sql_script|changed

  - name: create user
    shell: >
      source ~oracle/.bashrc && \
        sqlplus sys/{{ oracle_system_pwd }} as sysdba < /tmp/{{ schema_name }}_user.sql
    sudo_user: oracle
    register: create_user
    when: test_schema_sql_script|changed

  - name: create datadump directory
    shell: >
      source ~oracle/.bashrc && \
        sqlplus sys/{{ oracle_system_pwd }} as sysdba < /tmp/{{ schema_name }}_datadump.sql
    sudo_user: oracle
    when: test_datadump_sql_script|changed

  - name: load schema datadump
    shell: >
      source ~oracle/.bashrc && \
      impdp {{schema_name}}/password schemas={{schema_name}} directory={{schema_name}}_datadump dumpfile={{schema_name}}.dmp TABLE_EXISTS_ACTION=REPLACE
    sudo_user: root
    when: (create_user|changed) and (schema_dump|default("") != "")
