---

  # ================
  # transfer config
  # ----------------

  - name: verify if an update is needed
    shell: ls -ld {{artifactory_home}}/artifactory-* | grep -v {{artifactory_version}}
    ignore_errors: yes
    register: cmd_do_upgrade

  - name: stop artifactory before upgrade
    service: name=artifactory state=stopped
    when: cmd_do_upgrade.stdout

  - name: transfer configuration file with backup existing
    template:
      src=./templates/etc-opt-jfrog-artifactory-default.j2
      dest=/etc/opt/jfrog/artifactory/default
      backup=yes

  - name: transfer jdbc driver
    copy:
      src=./files/ojdbc6.jar
      dest={{artifactory_home}}/tomcat/lib/ojdbc6.jar

  - name: transfer over jdbc config with backup existing
    template:
      src=./templates/oracle.properties.j2
      dest={{artifactory_home}}/etc/storage.properties
      backup=yes
